spring:
  application:
    name: ws
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/websocket?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8
      username: root
      password: '123456'
server:
  port: 8080

